### ISSUE TITLE
Incorrect MillisecondTime calculations when running in linux.

### ISSUE THREAD

**Issue by DizzyDeveloper** [bamcis-io/amazon-dynamodb-lock-client#1]
Hey mate,

If you are still around and tinkering on this library could I ask you to update the 

**_LockClientUtils.MillisecondTime_**

At the moment it is: 

```c#
 public static long MillisecondTime()
 {
     return Stopwatch.GetTimestamp() / TimeSpan.TicksPerMillisecond;
 }
```

Could I get you to change it too:

```c#
 public static long MillisecondTime()
 {
     return Stopwatch.GetTimestamp() / (Stopwatch.Frequency / 1000);
 }
```

Stopwatch.GetTimestamp is environment related. i.e. so running it windows will produce one set of results while running it in linux will produce a different result.

The change just allows it be more environment agnostic as it.

**Comment by hakenmt** [comment]
Updated this in 1.0.1-beta. Thanks for pointing it out.
